name: customer_app
description: "KONFRM | GUEST — Native Customer Application Shell"
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.13.5
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_riverpod: ^2.6.1
  http: ^1.6.0
  intl: ^0.20.3
  konfrm_design_system:
    path: ../../packages/konfrm_design_system

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
