name: konfrm_design_system
description: "KONFRM Design System mobile foundation and component contracts."
version: 0.0.1
publish_to: 'none'

environment:
  sdk: ^3.13.5
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  fonts:
    - family: Cairo
      fonts:
        - asset: assets/fonts/Cairo-VariableFont.ttf
